BASE: ['resnet18_base.yaml']
DATA:
  BATCH_SIZE: 128
  DATASET: "medium_imagenet"
  IMG_SIZE: 64
  NUM_WORKERS: 32
  PIN_MEMORY: True
MODEL:
  NUM_CLASSES: 200
  RESUME: "/home/YSaxephone/sp26-nmep-hw3/output/resnet18/ckpt_best.pth"
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 0
  LR: 3e-3
  MIN_LR: 3e-3
  WARMUP_LR: 3e-3
OUTPUT: "output/resnet18_medium_imagenet"
SAVE_FREQ: 1
PRINT_FREQ: 500

# 5 epochs on 3e-3 before dropping to 3e-4
# changed l2-regularization and added label smoothing at epoch 15
# Added dropout and increased batch size at epoch 19